/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnOverviewRouteImport } from './routes/learn.overview'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeHiraganaRouteImport } from './routes/practice.hiragana'
import { Route as PracticeKanjiRouteImport } from './routes/practice.kanji'
import { Route as PracticeKatakanaRouteImport } from './routes/practice.katakana'
import { Route as PracticeVocabularyRouteImport } from './routes/practice.vocabulary'
import { Route as ReferencePhrasesRouteImport } from './routes/reference.phrases'
import { Route as LearnBookIdUnitIdRouteImport } from './routes/learn.$bookId.$unitId'
import { Route as LearnBookIdTestRouteImport } from './routes/learn.$bookId.test'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LearnRoute,
} as any)
const LearnOverviewRoute = LearnOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => LearnRoute,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeHiraganaRoute = PracticeHiraganaRouteImport.update({
  id: '/hiragana',
  path: '/hiragana',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeKanjiRoute = PracticeKanjiRouteImport.update({
  id: '/kanji',
  path: '/kanji',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeKatakanaRoute = PracticeKatakanaRouteImport.update({
  id: '/katakana',
  path: '/katakana',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeVocabularyRoute = PracticeVocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => PracticeRoute,
} as any)
const ReferencePhrasesRoute = ReferencePhrasesRouteImport.update({
  id: '/reference/phrases',
  path: '/reference/phrases',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnBookIdUnitIdRoute = LearnBookIdUnitIdRouteImport.update({
  id: '/$bookId/$unitId',
  path: '/$bookId/$unitId',
  getParentRoute: () => LearnRoute,
} as any)
const LearnBookIdTestRoute = LearnBookIdTestRouteImport.update({
  id: '/$bookId/test',
  path: '/$bookId/test',
  getParentRoute: () => LearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/learn/overview': typeof LearnOverviewRoute
  '/practice/hiragana': typeof PracticeHiraganaRoute
  '/practice/kanji': typeof PracticeKanjiRoute
  '/practice/katakana': typeof PracticeKatakanaRoute
  '/practice/vocabulary': typeof PracticeVocabularyRoute
  '/reference/phrases': typeof ReferencePhrasesRoute
  '/learn/': typeof LearnIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/learn/$bookId/$unitId': typeof LearnBookIdUnitIdRoute
  '/learn/$bookId/test': typeof LearnBookIdTestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/learn/overview': typeof LearnOverviewRoute
  '/practice/hiragana': typeof PracticeHiraganaRoute
  '/practice/kanji': typeof PracticeKanjiRoute
  '/practice/katakana': typeof PracticeKatakanaRoute
  '/practice/vocabulary': typeof PracticeVocabularyRoute
  '/reference/phrases': typeof ReferencePhrasesRoute
  '/learn': typeof LearnIndexRoute
  '/practice': typeof PracticeIndexRoute
  '/learn/$bookId/$unitId': typeof LearnBookIdUnitIdRoute
  '/learn/$bookId/test': typeof LearnBookIdTestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/learn': typeof LearnRouteWithChildren
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/learn/overview': typeof LearnOverviewRoute
  '/practice/hiragana': typeof PracticeHiraganaRoute
  '/practice/kanji': typeof PracticeKanjiRoute
  '/practice/katakana': typeof PracticeKatakanaRoute
  '/practice/vocabulary': typeof PracticeVocabularyRoute
  '/reference/phrases': typeof ReferencePhrasesRoute
  '/learn/': typeof LearnIndexRoute
  '/practice/': typeof PracticeIndexRoute
  '/learn/$bookId/$unitId': typeof LearnBookIdUnitIdRoute
  '/learn/$bookId/test': typeof LearnBookIdTestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/learn'
    | '/practice'
    | '/progress'
    | '/learn/overview'
    | '/practice/hiragana'
    | '/practice/kanji'
    | '/practice/katakana'
    | '/practice/vocabulary'
    | '/reference/phrases'
    | '/learn/'
    | '/practice/'
    | '/learn/$bookId/$unitId'
    | '/learn/$bookId/test'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/learn/overview'
    | '/practice/hiragana'
    | '/practice/kanji'
    | '/practice/katakana'
    | '/practice/vocabulary'
    | '/reference/phrases'
    | '/learn'
    | '/practice'
    | '/learn/$bookId/$unitId'
    | '/learn/$bookId/test'
  id:
    | '__root__'
    | '/'
    | '/learn'
    | '/practice'
    | '/progress'
    | '/learn/overview'
    | '/practice/hiragana'
    | '/practice/kanji'
    | '/practice/katakana'
    | '/practice/vocabulary'
    | '/reference/phrases'
    | '/learn/'
    | '/practice/'
    | '/learn/$bookId/$unitId'
    | '/learn/$bookId/test'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LearnRoute: typeof LearnRouteWithChildren
  PracticeRoute: typeof PracticeRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  ReferencePhrasesRoute: typeof ReferencePhrasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/overview': {
      id: '/learn/overview'
      path: '/overview'
      fullPath: '/learn/overview'
      preLoaderRoute: typeof LearnOverviewRouteImport
      parentRoute: typeof LearnRoute
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/hiragana': {
      id: '/practice/hiragana'
      path: '/hiragana'
      fullPath: '/practice/hiragana'
      preLoaderRoute: typeof PracticeHiraganaRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/kanji': {
      id: '/practice/kanji'
      path: '/kanji'
      fullPath: '/practice/kanji'
      preLoaderRoute: typeof PracticeKanjiRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/katakana': {
      id: '/practice/katakana'
      path: '/katakana'
      fullPath: '/practice/katakana'
      preLoaderRoute: typeof PracticeKatakanaRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/vocabulary': {
      id: '/practice/vocabulary'
      path: '/vocabulary'
      fullPath: '/practice/vocabulary'
      preLoaderRoute: typeof PracticeVocabularyRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/reference/phrases': {
      id: '/reference/phrases'
      path: '/reference/phrases'
      fullPath: '/reference/phrases'
      preLoaderRoute: typeof ReferencePhrasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$bookId/$unitId': {
      id: '/learn/$bookId/$unitId'
      path: '/$bookId/$unitId'
      fullPath: '/learn/$bookId/$unitId'
      preLoaderRoute: typeof LearnBookIdUnitIdRouteImport
      parentRoute: typeof LearnRoute
    }
    '/learn/$bookId/test': {
      id: '/learn/$bookId/test'
      path: '/$bookId/test'
      fullPath: '/learn/$bookId/test'
      preLoaderRoute: typeof LearnBookIdTestRouteImport
      parentRoute: typeof LearnRoute
    }
  }
}

interface LearnRouteChildren {
  LearnOverviewRoute: typeof LearnOverviewRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LearnBookIdUnitIdRoute: typeof LearnBookIdUnitIdRoute
  LearnBookIdTestRoute: typeof LearnBookIdTestRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnOverviewRoute: LearnOverviewRoute,
  LearnIndexRoute: LearnIndexRoute,
  LearnBookIdUnitIdRoute: LearnBookIdUnitIdRoute,
  LearnBookIdTestRoute: LearnBookIdTestRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface PracticeRouteChildren {
  PracticeHiraganaRoute: typeof PracticeHiraganaRoute
  PracticeKanjiRoute: typeof PracticeKanjiRoute
  PracticeKatakanaRoute: typeof PracticeKatakanaRoute
  PracticeVocabularyRoute: typeof PracticeVocabularyRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeHiraganaRoute: PracticeHiraganaRoute,
  PracticeKanjiRoute: PracticeKanjiRoute,
  PracticeKatakanaRoute: PracticeKatakanaRoute,
  PracticeVocabularyRoute: PracticeVocabularyRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LearnRoute: LearnRouteWithChildren,
  PracticeRoute: PracticeRouteWithChildren,
  ProgressRoute: ProgressRoute,
  ReferencePhrasesRoute: ReferencePhrasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
